env:
  browser: true
  commonjs: false
  es6: true
parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2020
  sourceType: module
rules:
  "@typescript-eslint/explicit-function-return-type":
    - warn
    - allowExpressions: true
  "@typescript-eslint/explicit-member-accessibility": off
  "@typescript-eslint/ban-types": off
  "@typescript-eslint/no-angle-bracket-type-assertion": off
  "@typescript-eslint/no-explicit-any": off
  "@typescript-eslint/no-non-null-assertion": off
  "@typescript-eslint/no-parameter-properties": off
  "@typescript-eslint/prefer-interface": off
  "@typescript-eslint/indent": off
overrides:
  - files:
      - "*.test.ts"
      - "*.spec.ts"
    rules:
      "@typescript-eslint/no-empty-function": off
      "@typescript-eslint/interface-name-prefix": off
